/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.api;

import merge_ats_client.ApiException;
import merge_ats_client.model.CommonModelScopes;
import merge_ats_client.model.CommonModelScopesUpdateSerializer;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommonModelScopesApi
 */
@Ignore
public class CommonModelScopesApiTest {

    private final CommonModelScopesApi api = new CommonModelScopesApi();

    
    /**
     * 
     *
     * Fetch the configuration of what data is saved by Merge when syncing. Common model scopes are set as a default across all linked accounts, but can be updated to have greater granularity per integration or account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void commonModelScopesRetrieveTest() throws ApiException {
        String integrationSlug = null;
        String linkedAccountId = null;
        CommonModelScopes response = api.commonModelScopesRetrieve(integrationSlug, linkedAccountId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update the configuration of what data is saved by Merge when syncing. Common model scopes are set as a default across all linked accounts, but can be updated to have greater granularity per integration or account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void commonModelScopesUpdateTest() throws ApiException {
        CommonModelScopesUpdateSerializer commonModelScopesUpdateSerializer = null;
        String integrationSlug = null;
        String linkedAccountId = null;
        CommonModelScopes response = api.commonModelScopesUpdate(commonModelScopesUpdateSerializer, integrationSlug, linkedAccountId);

        // TODO: test validations
    }
    
}
