/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.api;

import merge_ats_client.ApiException;
import org.threeten.bp.OffsetDateTime;
import merge_ats_client.model.PaginatedRemoteUserList;
import merge_ats_client.model.RemoteUser;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * 
     *
     * Returns a list of &#x60;RemoteUser&#x60; objects.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersListTest() throws ApiException {
        OffsetDateTime createdAfter = null;
        OffsetDateTime createdBefore = null;
        String cursor = null;
        String email = null;
        Boolean includeDeletedData = null;
        Boolean includeRemoteData = null;
        OffsetDateTime modifiedAfter = null;
        OffsetDateTime modifiedBefore = null;
        Integer pageSize = null;
        String remoteFields = null;
        String remoteId = null;
        PaginatedRemoteUserList response = api.usersList(createdAfter, createdBefore, cursor, email, includeDeletedData, includeRemoteData, modifiedAfter, modifiedBefore, pageSize, remoteFields, remoteId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns a &#x60;RemoteUser&#x60; object with the given &#x60;id&#x60;.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersRetrieveTest() throws ApiException {
        UUID id = null;
        Boolean includeRemoteData = null;
        String remoteFields = null;
        RemoteUser response = api.usersRetrieve(id, includeRemoteData, remoteFields);

        // TODO: test validations
    }
    
}
