/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package java.merge_ats_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.merge_ats_client.model.DisabilityStatusEnum;
import java.merge_ats_client.model.GenderEnum;
import java.merge_ats_client.model.RaceEnum;
import java.merge_ats_client.model.RemoteData;
import java.merge_ats_client.model.VeteranStatusEnum;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EEOC
 */
public class EEOCTest {
    private final EEOC model = new EEOC();

    /**
     * Model tests for EEOC
     */
    @Test
    public void testEEOC() {
        // TODO: test EEOC
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'candidate'
     */
    @Test
    public void candidateTest() {
        // TODO: test candidate
    }

    /**
     * Test the property 'submittedAt'
     */
    @Test
    public void submittedAtTest() {
        // TODO: test submittedAt
    }

    /**
     * Test the property 'race'
     */
    @Test
    public void raceTest() {
        // TODO: test race
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'veteranStatus'
     */
    @Test
    public void veteranStatusTest() {
        // TODO: test veteranStatus
    }

    /**
     * Test the property 'disabilityStatus'
     */
    @Test
    public void disabilityStatusTest() {
        // TODO: test disabilityStatus
    }

    /**
     * Test the property 'remoteData'
     */
    @Test
    public void remoteDataTest() {
        // TODO: test remoteData
    }

}
