/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import merge_ats_client.model.Candidate;
import merge_ats_client.model.ErrorValidationProblem;
import merge_ats_client.model.WarningValidationProblem;

/**
 * CandidateResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-11T15:52:25.875887Z[Etc/UTC]")
public class CandidateResponse {
  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  private Candidate model;

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  private List<WarningValidationProblem> warnings = new ArrayList<WarningValidationProblem>();

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<ErrorValidationProblem> errors = new ArrayList<ErrorValidationProblem>();


  public CandidateResponse model(Candidate model) {
    
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @ApiModelProperty(required = true, value = "")

  public Candidate getModel() {
    return model;
  }


  public void setModel(Candidate model) {
    this.model = model;
  }


  public CandidateResponse warnings(List<WarningValidationProblem> warnings) {
    
    this.warnings = warnings;
    return this;
  }

  public CandidateResponse addWarningsItem(WarningValidationProblem warningsItem) {
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * Get warnings
   * @return warnings
  **/
  @ApiModelProperty(required = true, value = "")

  public List<WarningValidationProblem> getWarnings() {
    return warnings;
  }


  public void setWarnings(List<WarningValidationProblem> warnings) {
    this.warnings = warnings;
  }


  public CandidateResponse errors(List<ErrorValidationProblem> errors) {
    
    this.errors = errors;
    return this;
  }

  public CandidateResponse addErrorsItem(ErrorValidationProblem errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ErrorValidationProblem> getErrors() {
    return errors;
  }


  public void setErrors(List<ErrorValidationProblem> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidateResponse candidateResponse = (CandidateResponse) o;
    return Objects.equals(this.model, candidateResponse.model) &&
        Objects.equals(this.warnings, candidateResponse.warnings) &&
        Objects.equals(this.errors, candidateResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, warnings, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateResponse {\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

