
/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import java.util.Objects;

import com.google.gson.JsonElement;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import merge_ats_client.JSON;
import org.threeten.bp.OffsetDateTime;

/**
 * CommonModelScopesScopeRawJson
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-10T20:48:58.736658Z[Etc/UTC]")
public class CommonModelScopesScopeRawJson {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private JsonElement type;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private JsonElement value;

  private transient JSON serializer;

  public CommonModelScopesScopeRawJson(JSON srlzer) { 
    
    this.serializer = srlzer;
  }

  public CommonModelScopesScopeRawJson type(TypeEnum type) {
    this.type = this.serializer.getGson().toJsonTree(type);
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public JsonElement getType() {
    return type;
  }
  public void setType(JsonElement type) {
    this.type = type;
  }

  public CommonModelScopesScopeRawJson value(String value) {
    this.value = this.serializer.getGson().toJsonTree(value);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public JsonElement getValue() {
    return value;
  }
  public void setValue(JsonElement value) {
    this.value = value;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonModelScopesScopeRawJson commonModelScopesScope = (CommonModelScopesScopeRawJson) o;
    return Objects.equals(this.type.getAsString(), commonModelScopesScope.type.getAsString()) &&
        Objects.equals(this.value.getAsString(), commonModelScopesScope.value.getAsString());
  }
  @Override
  public int hashCode() {
    return Objects.hash(type, value);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonModelScopesScopeRawJson {\n");
    sb.append("    type: ").append(toIndentedString(type.getAsString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value.getAsString())).append("\n");
    sb.append("}");
    return sb.toString();
  }
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}


