/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LinkToken
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-10T20:48:58.736658Z[Etc/UTC]")
public class LinkToken {
  public static final String SERIALIZED_NAME_LINK_TOKEN = "link_token";
  @SerializedName(SERIALIZED_NAME_LINK_TOKEN)
  private String linkToken;

  public static final String SERIALIZED_NAME_INTEGRATION_NAME = "integration_name";
  @SerializedName(SERIALIZED_NAME_INTEGRATION_NAME)
  private String integrationName;

  public static final String SERIALIZED_NAME_MAGIC_LINK_URL = "magic_link_url";
  @SerializedName(SERIALIZED_NAME_MAGIC_LINK_URL)
  private String magicLinkUrl;


  public LinkToken linkToken(String linkToken) {
    
    this.linkToken = linkToken;
    return this;
  }

   /**
   * Get linkToken
   * @return linkToken
  **/
  @ApiModelProperty(example = "necdP7FtdASl1fQwm62be2_dM4wBG8_GactqoUV0", required = true, value = "")

  public String getLinkToken() {
    return linkToken;
  }


  public void setLinkToken(String linkToken) {
    this.linkToken = linkToken;
  }


  public LinkToken integrationName(String integrationName) {
    
    this.integrationName = integrationName;
    return this;
  }

   /**
   * Get integrationName
   * @return integrationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lever", value = "")

  public String getIntegrationName() {
    return integrationName;
  }


  public void setIntegrationName(String integrationName) {
    this.integrationName = integrationName;
  }


  public LinkToken magicLinkUrl(String magicLinkUrl) {
    
    this.magicLinkUrl = magicLinkUrl;
    return this;
  }

   /**
   * Get magicLinkUrl
   * @return magicLinkUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://link.merge.dev/asdfjkl12345jsndfgi2i83n", value = "")

  public String getMagicLinkUrl() {
    return magicLinkUrl;
  }


  public void setMagicLinkUrl(String magicLinkUrl) {
    this.magicLinkUrl = magicLinkUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkToken linkToken = (LinkToken) o;
    return Objects.equals(this.linkToken, linkToken.linkToken) &&
        Objects.equals(this.integrationName, linkToken.integrationName) &&
        Objects.equals(this.magicLinkUrl, linkToken.magicLinkUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkToken, integrationName, magicLinkUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkToken {\n");
    sb.append("    linkToken: ").append(toIndentedString(linkToken)).append("\n");
    sb.append("    integrationName: ").append(toIndentedString(integrationName)).append("\n");
    sb.append("    magicLinkUrl: ").append(toIndentedString(magicLinkUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

