
/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import java.util.Objects;

import com.google.gson.JsonElement;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import merge_ats_client.JSON;
import org.threeten.bp.OffsetDateTime;

/**
 * # The RemoteUser Object ### Description The &#x60;RemoteUser&#x60; object is used to represent a third party user.  ### Usage Example Fetch from the &#x60;LIST RemoteUsers&#x60; endpoint to show all users for a third party.
 */
@ApiModel(description = "# The RemoteUser Object ### Description The `RemoteUser` object is used to represent a third party user.  ### Usage Example Fetch from the `LIST RemoteUsers` endpoint to show all users for a third party.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-07T18:32:11.741718Z[Etc/UTC]")
public class RemoteUserRawJson {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private JsonElement id;

  public static final String SERIALIZED_NAME_REMOTE_ID = "remote_id";
  @SerializedName(SERIALIZED_NAME_REMOTE_ID)
  private JsonElement remoteId;

  public static final String SERIALIZED_NAME_FIRST_NAME = "first_name";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private JsonElement firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "last_name";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private JsonElement lastName;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private JsonElement email;

  public static final String SERIALIZED_NAME_DISABLED = "disabled";
  @SerializedName(SERIALIZED_NAME_DISABLED)
  private JsonElement disabled;

  public static final String SERIALIZED_NAME_REMOTE_CREATED_AT = "remote_created_at";
  @SerializedName(SERIALIZED_NAME_REMOTE_CREATED_AT)
  private JsonElement remoteCreatedAt;

  public static final String SERIALIZED_NAME_ACCESS_ROLE = "access_role";
  @SerializedName(SERIALIZED_NAME_ACCESS_ROLE)
  private JsonElement accessRole;

  public static final String SERIALIZED_NAME_REMOTE_DATA = "remote_data";
  @SerializedName(SERIALIZED_NAME_REMOTE_DATA)
  private JsonElement remoteData;

  private transient JSON serializer;

  public RemoteUserRawJson(JSON srlzer) { 
    
    this.serializer = srlzer;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "b82302de-852e-4e60-b050-edf9da3b7c02", value = "")

  public JsonElement getId() {
    return id;
  }

  public RemoteUserRawJson remoteId(String remoteId) {
    this.remoteId = this.serializer.getGson().toJsonTree(remoteId);
    return this;
  }

   /**
   * The third-party API ID of the matching object.
   * @return remoteId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "344321", value = "The third-party API ID of the matching object.")

  public JsonElement getRemoteId() {
    return remoteId;
  }
  public void setRemoteId(JsonElement remoteId) {
    this.remoteId = remoteId;
  }

  public RemoteUserRawJson firstName(String firstName) {
    this.firstName = this.serializer.getGson().toJsonTree(firstName);
    return this;
  }

   /**
   * The user&#39;s first name.
   * @return firstName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Shensi", value = "The user's first name.")

  public JsonElement getFirstName() {
    return firstName;
  }
  public void setFirstName(JsonElement firstName) {
    this.firstName = firstName;
  }

  public RemoteUserRawJson lastName(String lastName) {
    this.lastName = this.serializer.getGson().toJsonTree(lastName);
    return this;
  }

   /**
   * The user&#39;s last name.
   * @return lastName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Ding", value = "The user's last name.")

  public JsonElement getLastName() {
    return lastName;
  }
  public void setLastName(JsonElement lastName) {
    this.lastName = lastName;
  }

  public RemoteUserRawJson email(String email) {
    this.email = this.serializer.getGson().toJsonTree(email);
    return this;
  }

   /**
   * The user&#39;s email.
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "hello@merge.dev", value = "The user's email.")

  public JsonElement getEmail() {
    return email;
  }
  public void setEmail(JsonElement email) {
    this.email = email;
  }

  public RemoteUserRawJson disabled(Boolean disabled) {
    this.disabled = this.serializer.getGson().toJsonTree(disabled);
    return this;
  }

   /**
   * Whether the user&#39;s account had been disabled.
   * @return disabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the user's account had been disabled.")

  public JsonElement getDisabled() {
    return disabled;
  }
  public void setDisabled(JsonElement disabled) {
    this.disabled = disabled;
  }

  public RemoteUserRawJson remoteCreatedAt(OffsetDateTime remoteCreatedAt) {
    this.remoteCreatedAt = this.serializer.getGson().toJsonTree(remoteCreatedAt);
    return this;
  }

   /**
   * When the third party&#39;s user was created.
   * @return remoteCreatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-11-10T00:00Z", value = "When the third party's user was created.")

  public JsonElement getRemoteCreatedAt() {
    return remoteCreatedAt;
  }
  public void setRemoteCreatedAt(JsonElement remoteCreatedAt) {
    this.remoteCreatedAt = remoteCreatedAt;
  }

  public RemoteUserRawJson accessRole(String accessRole) {
    this.accessRole = this.serializer.getGson().toJsonTree(accessRole);
    return this;
  }

   /**
   * Get accessRole
   * @return accessRole
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "SUPER_ADMIN", required = true, value = "")

  public JsonElement getAccessRole() {
    return accessRole;
  }
  public void setAccessRole(JsonElement accessRole) {
    this.accessRole = accessRole;
  }

   /**
   * Get remoteData
   * @return remoteData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"path\":\"/users\",\"data\":[\"Varies by platform\"]}]", value = "")

  public JsonElement getRemoteData() {
    return remoteData;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteUserRawJson remoteUser = (RemoteUserRawJson) o;
    return Objects.equals(this.id.getAsString(), remoteUser.id.getAsString()) &&
        Objects.equals(this.remoteId.getAsString(), remoteUser.remoteId.getAsString()) &&
        Objects.equals(this.firstName.getAsString(), remoteUser.firstName.getAsString()) &&
        Objects.equals(this.lastName.getAsString(), remoteUser.lastName.getAsString()) &&
        Objects.equals(this.email.getAsString(), remoteUser.email.getAsString()) &&
        Objects.equals(this.disabled.getAsString(), remoteUser.disabled.getAsString()) &&
        Objects.equals(this.remoteCreatedAt.getAsString(), remoteUser.remoteCreatedAt.getAsString()) &&
        Objects.equals(this.accessRole.getAsString(), remoteUser.accessRole.getAsString()) &&
        Objects.equals(this.remoteData.getAsString(), remoteUser.remoteData.getAsString());
  }
  @Override
  public int hashCode() {
    return Objects.hash(id, remoteId, firstName, lastName, email, disabled, remoteCreatedAt, accessRole, remoteData);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteUserRawJson {\n");
    sb.append("    id: ").append(toIndentedString(id.getAsString())).append("\n");
    sb.append("    remoteId: ").append(toIndentedString(remoteId.getAsString())).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName.getAsString())).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName.getAsString())).append("\n");
    sb.append("    email: ").append(toIndentedString(email.getAsString())).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled.getAsString())).append("\n");
    sb.append("    remoteCreatedAt: ").append(toIndentedString(remoteCreatedAt.getAsString())).append("\n");
    sb.append("    accessRole: ").append(toIndentedString(accessRole.getAsString())).append("\n");
    sb.append("    remoteData: ").append(toIndentedString(remoteData.getAsString())).append("\n");
    sb.append("}");
    return sb.toString();
  }
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}


