/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * UpdateApplicationStageRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-10T20:13:14.599893Z[Etc/UTC]")
public class UpdateApplicationStageRequest {
  public static final String SERIALIZED_NAME_JOB_INTERVIEW_STAGE = "job_interview_stage";
  @SerializedName(SERIALIZED_NAME_JOB_INTERVIEW_STAGE)
  private UUID jobInterviewStage;

  public static final String SERIALIZED_NAME_REMOTE_USER_ID = "remote_user_id";
  @SerializedName(SERIALIZED_NAME_REMOTE_USER_ID)
  private String remoteUserId;


  public UpdateApplicationStageRequest jobInterviewStage(UUID jobInterviewStage) {
    
    this.jobInterviewStage = jobInterviewStage;
    return this;
  }

   /**
   * The interview stage to move the application to.
   * @return jobInterviewStage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interview stage to move the application to.")

  public UUID getJobInterviewStage() {
    return jobInterviewStage;
  }


  public void setJobInterviewStage(UUID jobInterviewStage) {
    this.jobInterviewStage = jobInterviewStage;
  }


  public UpdateApplicationStageRequest remoteUserId(String remoteUserId) {
    
    this.remoteUserId = remoteUserId;
    return this;
  }

   /**
   * Get remoteUserId
   * @return remoteUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRemoteUserId() {
    return remoteUserId;
  }


  public void setRemoteUserId(String remoteUserId) {
    this.remoteUserId = remoteUserId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateApplicationStageRequest updateApplicationStageRequest = (UpdateApplicationStageRequest) o;
    return Objects.equals(this.jobInterviewStage, updateApplicationStageRequest.jobInterviewStage) &&
        Objects.equals(this.remoteUserId, updateApplicationStageRequest.remoteUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobInterviewStage, remoteUserId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateApplicationStageRequest {\n");
    sb.append("    jobInterviewStage: ").append(toIndentedString(jobInterviewStage)).append("\n");
    sb.append("    remoteUserId: ").append(toIndentedString(remoteUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

