
/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import java.util.Objects;

import com.google.gson.JsonElement;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import merge_ats_client.JSON;
import org.threeten.bp.OffsetDateTime;

/**
 * UpdateApplicationStageRequestRawJson
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-10T20:48:58.736658Z[Etc/UTC]")
public class UpdateApplicationStageRequestRawJson {
  public static final String SERIALIZED_NAME_JOB_INTERVIEW_STAGE = "job_interview_stage";
  @SerializedName(SERIALIZED_NAME_JOB_INTERVIEW_STAGE)
  private JsonElement jobInterviewStage;

  public static final String SERIALIZED_NAME_REMOTE_USER_ID = "remote_user_id";
  @SerializedName(SERIALIZED_NAME_REMOTE_USER_ID)
  private JsonElement remoteUserId;

  private transient JSON serializer;

  public UpdateApplicationStageRequestRawJson(JSON srlzer) { 
    
    this.serializer = srlzer;
  }

  public UpdateApplicationStageRequestRawJson jobInterviewStage(UUID jobInterviewStage) {
    this.jobInterviewStage = this.serializer.getGson().toJsonTree(jobInterviewStage);
    return this;
  }

   /**
   * The interview stage to move the application to.
   * @return jobInterviewStage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interview stage to move the application to.")

  public JsonElement getJobInterviewStage() {
    return jobInterviewStage;
  }
  public void setJobInterviewStage(JsonElement jobInterviewStage) {
    this.jobInterviewStage = jobInterviewStage;
  }

  public UpdateApplicationStageRequestRawJson remoteUserId(String remoteUserId) {
    this.remoteUserId = this.serializer.getGson().toJsonTree(remoteUserId);
    return this;
  }

   /**
   * Get remoteUserId
   * @return remoteUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JsonElement getRemoteUserId() {
    return remoteUserId;
  }
  public void setRemoteUserId(JsonElement remoteUserId) {
    this.remoteUserId = remoteUserId;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateApplicationStageRequestRawJson updateApplicationStageRequest = (UpdateApplicationStageRequestRawJson) o;
    return Objects.equals(this.jobInterviewStage.getAsString(), updateApplicationStageRequest.jobInterviewStage.getAsString()) &&
        Objects.equals(this.remoteUserId.getAsString(), updateApplicationStageRequest.remoteUserId.getAsString());
  }
  @Override
  public int hashCode() {
    return Objects.hash(jobInterviewStage, remoteUserId);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateApplicationStageRequestRawJson {\n");
    sb.append("    jobInterviewStage: ").append(toIndentedString(jobInterviewStage.getAsString())).append("\n");
    sb.append("    remoteUserId: ").append(toIndentedString(remoteUserId.getAsString())).append("\n");
    sb.append("}");
    return sb.toString();
  }
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}


