/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CommonModelScopesPutInnerDeserializerEnabledActionsEnum
 */
public class CommonModelScopesPutInnerDeserializerEnabledActionsEnumTest {
    /**
     * Model tests for CommonModelScopesPutInnerDeserializerEnabledActionsEnum
     */
    @Test
    public void testCommonModelScopesPutInnerDeserializerEnabledActionsEnum() {
        // TODO: test CommonModelScopesPutInnerDeserializerEnabledActionsEnum
    }

}
