/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import org.junit.Test;


/**
 * Model tests for EEOC
 */
public class EEOCTest {
    private final EEOC model = new EEOC();

    /**
     * Model tests for EEOC
     */
    @Test
    public void testEEOC() {
        // TODO: test EEOC
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'candidate'
     */
    @Test
    public void candidateTest() {
        // TODO: test candidate
    }

    /**
     * Test the property 'submittedAt'
     */
    @Test
    public void submittedAtTest() {
        // TODO: test submittedAt
    }

    /**
     * Test the property 'race'
     */
    @Test
    public void raceTest() {
        // TODO: test race
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'veteranStatus'
     */
    @Test
    public void veteranStatusTest() {
        // TODO: test veteranStatus
    }

    /**
     * Test the property 'disabilityStatus'
     */
    @Test
    public void disabilityStatusTest() {
        // TODO: test disabilityStatus
    }

    /**
     * Test the property 'remoteData'
     */
    @Test
    public void remoteDataTest() {
        // TODO: test remoteData
    }

}
