/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import merge_ats_client.model.RemoteData;
import merge_ats_client.model.ScheduledInterviewStatusEnum;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScheduledInterview
 */
public class ScheduledInterviewTest {
    private final ScheduledInterview model = new ScheduledInterview();

    /**
     * Model tests for ScheduledInterview
     */
    @Test
    public void testScheduledInterview() {
        // TODO: test ScheduledInterview
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'application'
     */
    @Test
    public void applicationTest() {
        // TODO: test application
    }

    /**
     * Test the property 'jobInterviewStage'
     */
    @Test
    public void jobInterviewStageTest() {
        // TODO: test jobInterviewStage
    }

    /**
     * Test the property 'organizer'
     */
    @Test
    public void organizerTest() {
        // TODO: test organizer
    }

    /**
     * Test the property 'interviewers'
     */
    @Test
    public void interviewersTest() {
        // TODO: test interviewers
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    public void startAtTest() {
        // TODO: test startAt
    }

    /**
     * Test the property 'endAt'
     */
    @Test
    public void endAtTest() {
        // TODO: test endAt
    }

    /**
     * Test the property 'remoteCreatedAt'
     */
    @Test
    public void remoteCreatedAtTest() {
        // TODO: test remoteCreatedAt
    }

    /**
     * Test the property 'remoteUpdatedAt'
     */
    @Test
    public void remoteUpdatedAtTest() {
        // TODO: test remoteUpdatedAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'remoteData'
     */
    @Test
    public void remoteDataTest() {
        // TODO: test remoteData
    }

}
