/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScorecardRequest
 */
public class ScorecardRequestTest {
    private final ScorecardRequest model = new ScorecardRequest();

    /**
     * Model tests for ScorecardRequest
     */
    @Test
    public void testScorecardRequest() {
        // TODO: test ScorecardRequest
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'application'
     */
    @Test
    public void applicationTest() {
        // TODO: test application
    }

    /**
     * Test the property 'interview'
     */
    @Test
    public void interviewTest() {
        // TODO: test interview
    }

    /**
     * Test the property 'interviewer'
     */
    @Test
    public void interviewerTest() {
        // TODO: test interviewer
    }

    /**
     * Test the property 'remoteCreatedAt'
     */
    @Test
    public void remoteCreatedAtTest() {
        // TODO: test remoteCreatedAt
    }

    /**
     * Test the property 'submittedAt'
     */
    @Test
    public void submittedAtTest() {
        // TODO: test submittedAt
    }

}
