/*
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_ats_client.model;

import java.net.URI;
import java.util.List;

import merge_ats_client.ApiClient;
import merge_ats_client.ApiException;
import merge_ats_client.Configuration;
import merge_ats_client.api.CandidatesApi;
import merge_ats_client.auth.ApiKeyAuth;
import org.junit.Test;


/**
 * Model tests for SyncStatus
 */
public class SyncStatusTest {
    private final SyncStatus model = new SyncStatus();

    /**
     * Model tests for SyncStatus
     */
    @Test
    public void testSyncStatus() {
        // TODO: test SyncStatus
    }

    /**
     * Test the property 'modelName'
     */
    @Test
    public void modelNameTest() {
        // TODO: test modelName
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property 'lastSyncStart'
     */
    @Test
    public void lastSyncStartTest() {
        // TODO: test lastSyncStart
    }

    /**
     * Test the property 'nextSyncStart'
     */
    @Test
    public void nextSyncStartTest() {
        // TODO: test nextSyncStart
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'isInitialSync'
     */
    @Test
    public void isInitialSyncTest() {
        // TODO: test isInitialSync
    }

}
